# Generated by Django 4.0.5 on 2022-06-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(max_length=3)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=100)),
                ('observação', models.CharField(max_length=300)),
            ],
        ),
    ]
