# Generated by Django 4.0.5 on 2022-06-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_alter_user_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='observação',
            new_name='observacao',
        ),
    ]
